title: patrickbrown-dev.github.io

name: Pat Brown
email: hello@patrickbrown.dev

description: ""

theme: minima
plugins:
  - jekyll-feed

github: patrickbrown-dev
mastodon:
 - username: patbrown
   instance: ruby.social

# For when minima 3.0 releases
minima:
  skin: auto
  social_links:
  - { platform: github,  user_url: "https://github.com/patrickbrown-dev" }
  - { platform: mastodon, user_url: "https://ruby.social/@patbrown" }

